In [28]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

##### TASK 1 #####
# Q1: Read the persona.csv file and show the general information about the dataset.
df = pd.read_csv("/content/persona.csv")
df

      PRICE   SOURCE     SEX COUNTRY  AGE
0        39  android    male     bra   17
1        39  android    male     bra   17
2        49  android    male     bra   17
3        29  android    male     tur   17
4        49  android    male     tur   17
...     ...      ...     ...     ...  ...
4995     29  android  female     bra   31
4996     29  android  female     bra   31
4997     29  android  female     bra   31
4998     39  android  female     bra   31
4999     29  android  female     bra   31

[5000 rows x 5 columns]

In [29]:
# Q2: How many unique SOURCE are there? What are their frequencies?
print(df["SOURCE"].nunique())
df["SOURCE"].value_counts()

2

android    2974
ios        2026
Name: SOURCE, dtype: int64

In [30]:
# Q3: How many unique PRICEs are there?
df["PRICE"].nunique()

6

In [31]:
# Q4: How many sales were made from which PRICE?
df["PRICE"].value_counts()

29    1305
39    1260
49    1031
19     992
59     212
9      200
Name: PRICE, dtype: int64

In [32]:
# Q5: How many sales were made from which country?
df["COUNTRY"].value_counts()

usa    2065
bra    1496
deu     455
tur     451
fra     303
can     230
Name: COUNTRY, dtype: int64

In [33]:
# Q6: How much was earned in total from sales by country?
df.groupby("COUNTRY").agg({"PRICE": ["sum"]})

         PRICE
           sum
COUNTRY
bra      51354
can       7730
deu      15485
fra      10177
tur      15689
usa      70225

In [34]:
# Q7: What are the sales numbers by SOURCE types?
df["SOURCE"].value_counts()

android    2974
ios        2026
Name: SOURCE, dtype: int64

In [35]:
# Q8: What are the PRICE averages by country?
df.groupby("COUNTRY").agg({"PRICE": ["mean"]})

             PRICE
              mean
COUNTRY
bra      34.327540
can      33.608696
deu      34.032967
fra      33.587459
tur      34.787140
usa      34.007264

In [36]:
# Q9: What are the PRICE averages according to SOURCEs?
df.groupby("SOURCE").agg({"PRICE": ["mean"]})

             PRICE
              mean
SOURCE
android  34.174849
ios      34.069102

In [37]:
# Q10: What are the PRICE averages in the COUNTRY-SOURCE breakdown?
df.groupby(["COUNTRY","SOURCE"]).agg({"PRICE": ["mean"]})

                     PRICE
                      mean
COUNTRY SOURCE
bra     android  34.387029
        ios      34.222222
can     android  33.330709
        ios      33.951456
deu     android  33.869888
        ios      34.268817
fra     android  34.312500
        ios      32.776224
tur     android  36.229437
        ios      33.272727
usa     android  33.760357
        ios      34.371703

In [38]:
##### Task 2: What are the average earnings in breakdown of COUNTRY, SOURCE, SEX, AGE? #####
agg_df = df.groupby(["COUNTRY","SOURCE","SEX", "AGE"]).agg({"PRICE": "mean"})

In [39]:
##### Task 3: Sort the output according to PRICE. #####
agg_df.sort_values("PRICE", ascending=False)

                            PRICE
COUNTRY SOURCE  SEX    AGE
bra     android male   46    59.0
usa     android male   36    59.0
fra     android female 24    59.0
usa     ios     male   32    54.0
deu     android female 36    49.0
...                           ...
usa     ios     female 38    19.0
                       30    19.0
can     android female 27    19.0
fra     android male   18    19.0
deu     android male   26     9.0

[348 rows x 1 columns]

In [40]:
##### Task 4: Convert the names in the index to variable names. #####
agg_df = agg_df.reset_index()
agg_df

    COUNTRY   SOURCE     SEX  AGE      PRICE
0       bra  android  female   15  38.714286
1       bra  android  female   16  35.944444
2       bra  android  female   17  35.666667
3       bra  android  female   18  32.255814
4       bra  android  female   19  35.206897
..      ...      ...     ...  ...        ...
343     usa      ios    male   42  30.250000
344     usa      ios    male   50  39.000000
345     usa      ios    male   53  34.000000
346     usa      ios    male   55  29.000000
347     usa      ios    male   59  46.500000

[348 rows x 5 columns]

In [42]:
##### Task 5: Convert age variable to categorical variable and add it to agg_df. #####
bins = [0, 18, 23, 30, 40, agg_df["AGE"].max()]
labels = ["0_18", "19_23", "24_30", "31_40", "41"+str(agg_df["AGE"].max())]
agg_df["AGE_CAT"] = pd.cut(agg_df["AGE"], bins=bins, labels=labels)
agg_df

    COUNTRY   SOURCE     SEX  AGE      PRICE AGE_CAT
0       bra  android  female   15  38.714286    0_18
1       bra  android  female   16  35.944444    0_18
2       bra  android  female   17  35.666667    0_18
3       bra  android  female   18  32.255814    0_18
4       bra  android  female   19  35.206897   19_23
..      ...      ...     ...  ...        ...     ...
343     usa      ios    male   42  30.250000    4166
344     usa      ios    male   50  39.000000    4166
345     usa      ios    male   53  34.000000    4166
346     usa      ios    male   55  29.000000    4166
347     usa      ios    male   59  46.500000    4166

[348 rows x 6 columns]

In [43]:
##### Task 6: Identify new level-based customers (personas). #####
agg_df["CUSTOMERS_LEVEL_BASED"] = ["_".join(i).upper() for i in agg_df.drop(["PRICE", "AGE"], axis=1).values]
agg_df = agg_df[["CUSTOMERS_LEVEL_BASED", "PRICE"]].groupby("CUSTOMERS_LEVEL_BASED")["PRICE"].mean().reset_index()
agg_df

        CUSTOMERS_LEVEL_BASED      PRICE
0     BRA_ANDROID_FEMALE_0_18  35.645303
1    BRA_ANDROID_FEMALE_19_23  34.077340
2    BRA_ANDROID_FEMALE_24_30  33.863946
3    BRA_ANDROID_FEMALE_31_40  34.898326
4     BRA_ANDROID_FEMALE_4166  36.737179
..                        ...        ...
104         USA_IOS_MALE_0_18  33.983495
105        USA_IOS_MALE_19_23  34.901872
106        USA_IOS_MALE_24_30  34.838143
107        USA_IOS_MALE_31_40  36.206324
108         USA_IOS_MALE_4166  35.750000

[109 rows x 2 columns]

In [47]:
##### Task 7: Segment new customers (personas). #####
agg_df["SEGMENT"] = pd.qcut(agg_df["PRICE"], q=4, labels=["D", "C", "B", "A"])
agg_df.groupby("SEGMENT").agg({"PRICE": ["mean", "max", "min"]}).reset_index()

  SEGMENT      PRICE
                mean        max        min
0       D  29.206780  32.333333  19.000000
1       C  33.509674  34.077340  32.500000
2       B  34.999645  36.000000  34.103727
3       A  38.691234  45.428571  36.060606

In [51]:
##### Task 8: Categorize new customers and estimate how much revenue they can generate. #####
new_user = "TUR_ANDROID_FEMALE_31_40"
agg_df[agg_df["CUSTOMERS_LEVEL_BASED"] == new_user]

new_user2 = "FRA_IOS_FEMALE_31_40"
agg_df[agg_df["CUSTOMERS_LEVEL_BASED"] == new_user2]

df[["PRICE", "AGE"]].corr()

          PRICE       AGE
PRICE  1.000000 -0.010202
AGE   -0.010202  1.000000